use std::collections::HashMap;
use std::sync::LazyLock;

#[derive(Debug, Clone, PartialEq)]
pub struct Country {
    pub name: String,              // 2-letter lowercase (e.g. "no")
    pub three_letter_code: String, // 3-letter uppercase (e.g. "NOR")
}

/// Complete ISO 3166-1 alpha-2 to alpha-3 mapping (matching Java's Locale.getISOCountries()).
static COUNTRIES: LazyLock<HashMap<&'static str, (&'static str, &'static str)>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("ad", ("ad", "AND"));
    m.insert("ae", ("ae", "ARE"));
    m.insert("af", ("af", "AFG"));
    m.insert("ag", ("ag", "ATG"));
    m.insert("ai", ("ai", "AIA"));
    m.insert("al", ("al", "ALB"));
    m.insert("am", ("am", "ARM"));
    m.insert("ao", ("ao", "AGO"));
    m.insert("aq", ("aq", "ATA"));
    m.insert("ar", ("ar", "ARG"));
    m.insert("as", ("as", "ASM"));
    m.insert("at", ("at", "AUT"));
    m.insert("au", ("au", "AUS"));
    m.insert("aw", ("aw", "ABW"));
    m.insert("ax", ("ax", "ALA"));
    m.insert("az", ("az", "AZE"));
    m.insert("ba", ("ba", "BIH"));
    m.insert("bb", ("bb", "BRB"));
    m.insert("bd", ("bd", "BGD"));
    m.insert("be", ("be", "BEL"));
    m.insert("bf", ("bf", "BFA"));
    m.insert("bg", ("bg", "BGR"));
    m.insert("bh", ("bh", "BHR"));
    m.insert("bi", ("bi", "BDI"));
    m.insert("bj", ("bj", "BEN"));
    m.insert("bl", ("bl", "BLM"));
    m.insert("bm", ("bm", "BMU"));
    m.insert("bn", ("bn", "BRN"));
    m.insert("bo", ("bo", "BOL"));
    m.insert("bq", ("bq", "BES"));
    m.insert("br", ("br", "BRA"));
    m.insert("bs", ("bs", "BHS"));
    m.insert("bt", ("bt", "BTN"));
    m.insert("bv", ("bv", "BVT"));
    m.insert("bw", ("bw", "BWA"));
    m.insert("by", ("by", "BLR"));
    m.insert("bz", ("bz", "BLZ"));
    m.insert("ca", ("ca", "CAN"));
    m.insert("cc", ("cc", "CCK"));
    m.insert("cd", ("cd", "COD"));
    m.insert("cf", ("cf", "CAF"));
    m.insert("cg", ("cg", "COG"));
    m.insert("ch", ("ch", "CHE"));
    m.insert("ci", ("ci", "CIV"));
    m.insert("ck", ("ck", "COK"));
    m.insert("cl", ("cl", "CHL"));
    m.insert("cm", ("cm", "CMR"));
    m.insert("cn", ("cn", "CHN"));
    m.insert("co", ("co", "COL"));
    m.insert("cr", ("cr", "CRI"));
    m.insert("cu", ("cu", "CUB"));
    m.insert("cv", ("cv", "CPV"));
    m.insert("cw", ("cw", "CUW"));
    m.insert("cx", ("cx", "CXR"));
    m.insert("cy", ("cy", "CYP"));
    m.insert("cz", ("cz", "CZE"));
    m.insert("de", ("de", "DEU"));
    m.insert("dj", ("dj", "DJI"));
    m.insert("dk", ("dk", "DNK"));
    m.insert("dm", ("dm", "DMA"));
    m.insert("do", ("do", "DOM"));
    m.insert("dz", ("dz", "DZA"));
    m.insert("ec", ("ec", "ECU"));
    m.insert("ee", ("ee", "EST"));
    m.insert("eg", ("eg", "EGY"));
    m.insert("eh", ("eh", "ESH"));
    m.insert("er", ("er", "ERI"));
    m.insert("es", ("es", "ESP"));
    m.insert("et", ("et", "ETH"));
    m.insert("fi", ("fi", "FIN"));
    m.insert("fj", ("fj", "FJI"));
    m.insert("fk", ("fk", "FLK"));
    m.insert("fm", ("fm", "FSM"));
    m.insert("fo", ("fo", "FRO"));
    m.insert("fr", ("fr", "FRA"));
    m.insert("ga", ("ga", "GAB"));
    m.insert("gb", ("gb", "GBR"));
    m.insert("gd", ("gd", "GRD"));
    m.insert("ge", ("ge", "GEO"));
    m.insert("gf", ("gf", "GUF"));
    m.insert("gg", ("gg", "GGY"));
    m.insert("gh", ("gh", "GHA"));
    m.insert("gi", ("gi", "GIB"));
    m.insert("gl", ("gl", "GRL"));
    m.insert("gm", ("gm", "GMB"));
    m.insert("gn", ("gn", "GIN"));
    m.insert("gp", ("gp", "GLP"));
    m.insert("gq", ("gq", "GNQ"));
    m.insert("gr", ("gr", "GRC"));
    m.insert("gs", ("gs", "SGS"));
    m.insert("gt", ("gt", "GTM"));
    m.insert("gu", ("gu", "GUM"));
    m.insert("gw", ("gw", "GNB"));
    m.insert("gy", ("gy", "GUY"));
    m.insert("hk", ("hk", "HKG"));
    m.insert("hm", ("hm", "HMD"));
    m.insert("hn", ("hn", "HND"));
    m.insert("hr", ("hr", "HRV"));
    m.insert("ht", ("ht", "HTI"));
    m.insert("hu", ("hu", "HUN"));
    m.insert("id", ("id", "IDN"));
    m.insert("ie", ("ie", "IRL"));
    m.insert("il", ("il", "ISR"));
    m.insert("im", ("im", "IMN"));
    m.insert("in", ("in", "IND"));
    m.insert("io", ("io", "IOT"));
    m.insert("iq", ("iq", "IRQ"));
    m.insert("ir", ("ir", "IRN"));
    m.insert("is", ("is", "ISL"));
    m.insert("it", ("it", "ITA"));
    m.insert("je", ("je", "JEY"));
    m.insert("jm", ("jm", "JAM"));
    m.insert("jo", ("jo", "JOR"));
    m.insert("jp", ("jp", "JPN"));
    m.insert("ke", ("ke", "KEN"));
    m.insert("kg", ("kg", "KGZ"));
    m.insert("kh", ("kh", "KHM"));
    m.insert("ki", ("ki", "KIR"));
    m.insert("km", ("km", "COM"));
    m.insert("kn", ("kn", "KNA"));
    m.insert("kp", ("kp", "PRK"));
    m.insert("kr", ("kr", "KOR"));
    m.insert("kw", ("kw", "KWT"));
    m.insert("ky", ("ky", "CYM"));
    m.insert("kz", ("kz", "KAZ"));
    m.insert("la", ("la", "LAO"));
    m.insert("lb", ("lb", "LBN"));
    m.insert("lc", ("lc", "LCA"));
    m.insert("li", ("li", "LIE"));
    m.insert("lk", ("lk", "LKA"));
    m.insert("lr", ("lr", "LBR"));
    m.insert("ls", ("ls", "LSO"));
    m.insert("lt", ("lt", "LTU"));
    m.insert("lu", ("lu", "LUX"));
    m.insert("lv", ("lv", "LVA"));
    m.insert("ly", ("ly", "LBY"));
    m.insert("ma", ("ma", "MAR"));
    m.insert("mc", ("mc", "MCO"));
    m.insert("md", ("md", "MDA"));
    m.insert("me", ("me", "MNE"));
    m.insert("mf", ("mf", "MAF"));
    m.insert("mg", ("mg", "MDG"));
    m.insert("mh", ("mh", "MHL"));
    m.insert("mk", ("mk", "MKD"));
    m.insert("ml", ("ml", "MLI"));
    m.insert("mm", ("mm", "MMR"));
    m.insert("mn", ("mn", "MNG"));
    m.insert("mo", ("mo", "MAC"));
    m.insert("mp", ("mp", "MNP"));
    m.insert("mq", ("mq", "MTQ"));
    m.insert("mr", ("mr", "MRT"));
    m.insert("ms", ("ms", "MSR"));
    m.insert("mt", ("mt", "MLT"));
    m.insert("mu", ("mu", "MUS"));
    m.insert("mv", ("mv", "MDV"));
    m.insert("mw", ("mw", "MWI"));
    m.insert("mx", ("mx", "MEX"));
    m.insert("my", ("my", "MYS"));
    m.insert("mz", ("mz", "MOZ"));
    m.insert("na", ("na", "NAM"));
    m.insert("nc", ("nc", "NCL"));
    m.insert("ne", ("ne", "NER"));
    m.insert("nf", ("nf", "NFK"));
    m.insert("ng", ("ng", "NGA"));
    m.insert("ni", ("ni", "NIC"));
    m.insert("nl", ("nl", "NLD"));
    m.insert("no", ("no", "NOR"));
    m.insert("np", ("np", "NPL"));
    m.insert("nr", ("nr", "NRU"));
    m.insert("nu", ("nu", "NIU"));
    m.insert("nz", ("nz", "NZL"));
    m.insert("om", ("om", "OMN"));
    m.insert("pa", ("pa", "PAN"));
    m.insert("pe", ("pe", "PER"));
    m.insert("pf", ("pf", "PYF"));
    m.insert("pg", ("pg", "PNG"));
    m.insert("ph", ("ph", "PHL"));
    m.insert("pk", ("pk", "PAK"));
    m.insert("pl", ("pl", "POL"));
    m.insert("pm", ("pm", "SPM"));
    m.insert("pn", ("pn", "PCN"));
    m.insert("pr", ("pr", "PRI"));
    m.insert("ps", ("ps", "PSE"));
    m.insert("pt", ("pt", "PRT"));
    m.insert("pw", ("pw", "PLW"));
    m.insert("py", ("py", "PRY"));
    m.insert("qa", ("qa", "QAT"));
    m.insert("re", ("re", "REU"));
    m.insert("ro", ("ro", "ROU"));
    m.insert("rs", ("rs", "SRB"));
    m.insert("ru", ("ru", "RUS"));
    m.insert("rw", ("rw", "RWA"));
    m.insert("sa", ("sa", "SAU"));
    m.insert("sb", ("sb", "SLB"));
    m.insert("sc", ("sc", "SYC"));
    m.insert("sd", ("sd", "SDN"));
    m.insert("se", ("se", "SWE"));
    m.insert("sg", ("sg", "SGP"));
    m.insert("sh", ("sh", "SHN"));
    m.insert("si", ("si", "SVN"));
    m.insert("sj", ("sj", "SJM"));
    m.insert("sk", ("sk", "SVK"));
    m.insert("sl", ("sl", "SLE"));
    m.insert("sm", ("sm", "SMR"));
    m.insert("sn", ("sn", "SEN"));
    m.insert("so", ("so", "SOM"));
    m.insert("sr", ("sr", "SUR"));
    m.insert("ss", ("ss", "SSD"));
    m.insert("st", ("st", "STP"));
    m.insert("sv", ("sv", "SLV"));
    m.insert("sx", ("sx", "SXM"));
    m.insert("sy", ("sy", "SYR"));
    m.insert("sz", ("sz", "SWZ"));
    m.insert("tc", ("tc", "TCA"));
    m.insert("td", ("td", "TCD"));
    m.insert("tf", ("tf", "ATF"));
    m.insert("tg", ("tg", "TGO"));
    m.insert("th", ("th", "THA"));
    m.insert("tj", ("tj", "TJK"));
    m.insert("tk", ("tk", "TKL"));
    m.insert("tl", ("tl", "TLS"));
    m.insert("tm", ("tm", "TKM"));
    m.insert("tn", ("tn", "TUN"));
    m.insert("to", ("to", "TON"));
    m.insert("tr", ("tr", "TUR"));
    m.insert("tt", ("tt", "TTO"));
    m.insert("tv", ("tv", "TUV"));
    m.insert("tw", ("tw", "TWN"));
    m.insert("tz", ("tz", "TZA"));
    m.insert("ua", ("ua", "UKR"));
    m.insert("ug", ("ug", "UGA"));
    m.insert("um", ("um", "UMI"));
    m.insert("us", ("us", "USA"));
    m.insert("uy", ("uy", "URY"));
    m.insert("uz", ("uz", "UZB"));
    m.insert("va", ("va", "VAT"));
    m.insert("vc", ("vc", "VCT"));
    m.insert("ve", ("ve", "VEN"));
    m.insert("vg", ("vg", "VGB"));
    m.insert("vi", ("vi", "VIR"));
    m.insert("vn", ("vn", "VNM"));
    m.insert("vu", ("vu", "VUT"));
    m.insert("wf", ("wf", "WLF"));
    m.insert("ws", ("ws", "WSM"));
    m.insert("ye", ("ye", "YEM"));
    m.insert("yt", ("yt", "MYT"));
    m.insert("za", ("za", "ZAF"));
    m.insert("zm", ("zm", "ZMB"));
    m.insert("zw", ("zw", "ZWE"));
    m
});

impl Country {
    pub fn no() -> Self {
        Self { name: "no".to_string(), three_letter_code: "NOR".to_string() }
    }

    pub fn parse(code: Option<&str>) -> Option<Self> {
        let code = code?.to_lowercase();
        let key = code.as_str();
        COUNTRIES.get(key).map(|(name, three)| Country {
            name: name.to_string(),
            three_letter_code: three.to_string(),
        })
    }
}
